version: "3"
services:
  server:
    env_file:
      - .env
    build:
      args:
        JAVA_VERSION: ${JAVA_VERSION}
      context: .
      dockerfile: ./.docker/Dockerfile
    volumes:
      - ./server:/home/container
    stdin_open: true
    tty: true
